apiVersion: apps/v1
kind: Deployment
metadata:
  name: skinet-redis
  labels:
    app: skinet
    tier: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skinet
      tier: cache
  template:
    metadata:
      labels:
        app: skinet
        tier: cache
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: redis:alpine
        name: skinet-redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
     app: skinet
spec:
  type: LoadBalancer
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: skinet
    tier: cache