apiVersion: apps/v1
kind: Deployment
metadata:
  name: skinet-sql
  labels:
    app: skinet
    tier: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skinet
      tier: sql
  template:
    metadata:
      labels:
        app: skinet
        tier: sql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mcr.microsoft.com/mssql/server:2017-latest
        name: skinet-sql
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        ports:
        - containerPort: 1433
          name: sql
        volumeMounts:
        - name: sql-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: sql-persistent-storage
        persistentVolumeClaim:
          claimName: skinet-sql-pvc